server:
  servlet:
    context-path: /qgywork
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work_order_memo?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null  # json 全局配置 不反回为null的字段

